#!/bin/bash
BACKUP_NAME="$1"
shift
BORG_PASSPHRASE=$(cat ~/.borg-passphrase) BORG_REPO=$(cat ~/.borg-repository) borg create -s --list --compression auto,lzma,5 ::{hostname}-{user}-$BACKUP_NAME-{now} $@
